export const ACTIONS = {
  // TOGGLE_SIDE_NAV: 'APP/TOGGLE_SIDE_NAV',
  // TOGGLE_DELETE_MODE: 'APP/TOGGLE_DELETE_MODE',
  // MARK_FOR_DELETE: 'APP/MARK_FOR_DELETE',
  HEADER_TITLE: 'APP/HEADER_TITLE',
  TOGGLE_DEV_MODE: 'APP/TOGGLE_DEV_MODE',
};
// export const SIDE_NAV_WIDTH = 250;
// export const SIDE_NAV_COLLAPSE_WIDTH = 64;
