export const ACTIONS = {
  TOGGLE_SIDE_NAV: 'APP/TOGGLE_SIDE_NAV',
  TOGGLE_DELETE_MODE: 'ADMIN/TOGGLE_DELETE_MODE',
  MARK_FOR_DELETE: 'ADMIN/MARK_FOR_DELETE',
};
export const SIDE_NAV_WIDTH = 250;
export const SIDE_NAV_COLLAPSE_WIDTH = 54;
