export const ACTIONS = {
  TOGGLE_SIDE_NAV: 'APP/TOGGLE_SIDE_NAV',
  TOGGLE_DELETE_MODE: 'APP/TOGGLE_DELETE_MODE',
  MARK_FOR_DELETE: 'APP/MARK_FOR_DELETE',
  STORE_DELETED_IDS_HACK: 'APP/STORE_DELETED_IDS_HACK',
};
export const SIDE_NAV_WIDTH = 250;
export const SIDE_NAV_COLLAPSE_WIDTH = 54;
